- examples/gke/tgi-from-gcs-deployment/README.md
As internally reported by Wenlei (Frank) He, this PR fixes a wrong path to the `scripts/upload_model_to_gcs.sh` script within the TGI from GCS example.
> Update path to `scripts/upload_model_to_gcs.sh`

- README.md
- containers/pytorch/inference/README.md
- examples/vertex-ai/notebooks/deploy-bert-on-vertex-ai/vertex-notebook.ipynb
This PR updates some `README.md` files and references to the Hugging Face PyTorch DLC for Inference, since those were pointing to the previous version of the container being `us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-pytorch-inference-cpu.2-2.transformers.4-41.ubuntu2204.py311` and `us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-pytorch-inference-cu121.2-2.transformers.4-41.ubuntu2204.py311` for both CPU and GPU, respectively.
Now pointing to the latest `us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-pytorch-inference-cpu.2-2.transformers.4-44.ubuntu2204.py311` and `us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-pytorch-inference-cu121.2-2.transformers.4-44.ubuntu2204.py311` for both CPU and GPU, …
> Update as of latest PyTorch Inference release

- containers/README.md
- containers/pytorch/training/README.md
- containers/tei/README.md
- examples/gke/README.md
- examples/gke/tei-deployment/README.md
- examples/gke/tei-from-gcs-deployment/README.md
- examples/gke/tgi-deployment/README.md
- examples/gke/tgi-from-gcs-deployment/README.md
- examples/gke/trl-full-fine-tuning/README.md
- examples/gke/trl-lora-fine-tuning/README.md
- examples/vertex-ai/README.md
- examples/vertex-ai/notebooks/deploy-bert-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/deploy-embedding-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/deploy-gemma-from-gcs-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/deploy-gemma-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/trl-full-sft-fine-tuning-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/trl-lora-sft-fine-tuning-on-vertex-ai/vertex-notebook.ipynb
This PR adds the missing `gcloud auth application-default login` command to both the Google Kubernetes Engine (GKE) and Vertex AI examples, so as to ensure that when running the examples locally via a Google Cloud account the credentials are there. Otherwise an authentication error will be raised stating that the default credentials were not found.
This PR also updates and aligns the formatting of the existing `README.md` files; and applies minor fixes and improvements to some of the `vertex-notebook.ipynb` files.
Kudos to @philschmid for the fixes and improvements!
> Revision some `README.md` and `vertex-notebook.ipynb` files

- .github/workflows/trufflehog.yml
This PR adds [`trufflehog`](https://github.com/trufflesecurity/trufflehog) to scan for leaked secrets, since every example within this repository needs secrets to run and leaks can eventually happen (ideally those won't, but just in case 🤞🏻).
Also the addition of `trufflehog` is a security recommendation and is included in some other Hugging Face repositories as [`text-embeddings-inference`](https://github.com/huggingface/text-embeddings-inference).
> Add `.github/workflows/trufflehog.yml`

- examples/gke/tei-deployment/README.md
- examples/gke/tei-from-gcs-deployment/README.md
- examples/gke/tgi-deployment/README.md
- examples/gke/tgi-from-gcs-deployment/README.md
- examples/gke/trl-full-fine-tuning/README.md
- examples/gke/trl-lora-fine-tuning/README.md
This PR sets the flag `--no-autoprovisioning-enable-insecure-kubelet-readonly-port` within the `gcloud container clusters create-auto` command, so that the `kubelet` read-only port 10255 is not exposed as it's not considered secure.
More information in the [Google Kubernetes Engine (GKE) Documentation - Disable the kubelet read-only port in GKE clusters](https://cloud.google.com/kubernetes-engine/docs/how-to/disable-kubelet-readonly-port).
Closes #94
> Disable insecure `kubelet` read-only 10255 port

- examples/cloud-run/tgi-deployment/README.md
A couple of additional suggestions:
1. when using cloud workstations or cloud shell, the (bash) terminal doesn't get the contents of the $ACCESS_TOKEN before sending the cURL request. The result is always `Your client does not have permission to the requested URL <code>/v1/chat/completions</code>.` which might be difficult to debug since the Access Token is valid. I believe using double-quotes here works fine for other shells.
2. The minimum requirements for GPUs is 4 CPU and 16 memory. I've updated the gcloud command and clarified the description to call out how this is the minimum requirement.
> small updates to the TGI Cloud Run readme

- examples/gke/tei-deployment/cpu-config/ingress.yaml
- examples/gke/tei-deployment/gpu-config/ingress.yaml
- examples/gke/tei-from-gcs-deployment/cpu-config/ingress.yaml
- examples/gke/tei-from-gcs-deployment/gpu-config/ingress.yaml
- examples/gke/tgi-deployment/config/ingress.yaml
- examples/gke/tgi-from-gcs-deployment/config/ingress.yaml
This PR reverts the PR #107, since even though it's deprecated in Kubernetes; it needs to be specified via the `annotations` for it to work on Google Kubernetes Engine (GKE).
Now a note has been included so that the `DeprecationWarning` is ignored.
More information at
https://cloud.google.com/kubernetes-engine/docs/concepts/ingress
> Revert `ingressClassName` over `annotation`

- docs/scripts/auto-generate-examples.py
Hot-fix `docs/scripts/auto-generate-examples.py` script as the `GITHUB_BRANCH` environment variable is empty, so rollback to use `main` by default which is not ideal either since the PR examples won't have working images, but lets tackle this on another PR later on.
> Fix `docs/scripts/auto-generate-examples.py`

- examples/gke/tei-deployment/README.md
- examples/gke/tei-from-gcs-deployment/README.md
- examples/gke/tgi-deployment/README.md
- examples/gke/tgi-from-gcs-deployment/README.md
- examples/gke/tgi-llama-405b-deployment/README.md
- examples/gke/tgi-llama-vision-deployment/README.md
- examples/gke/tgi-multi-lora-deployment/README.md
- examples/gke/trl-full-fine-tuning/README.md
- examples/gke/trl-lora-fine-tuning/README.md
This PR updates the `examples/gke/**/README.md` files so as to include relative links to the Kubernetes files used within the examples, which are automatically translated with [`docs/scripts/auto-generate-examples.py`](https://github.com/huggingface/Google-Cloud-Containers/blob/main/docs/scripts/auto-generate-examples.py) from relative paths into URLs.
Thanks to @philschmid for catching that!
> Update `examples/gke` to include paths to Kubernetes files

- docs/scripts/auto-generate-examples.py
- examples/vertex-ai/notebooks/deploy-bert-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/deploy-embedding-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/deploy-flux-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/deploy-llama-3-1-405b-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/deploy-llama-vision-on-vertex-ai/vertex-notebook.ipynb
- examples/vertex-ai/notebooks/evaluate-llms-with-vertex-ai/vertex-notebook.ipynb
This PR adds a note at the end of all the auto-generated examples, so that those come with a GitHub reference to the actual example files in this repository.
Additionally, some `WARNING` messages have been fixed since those were using the notation `> [!WARN]` which is wrong, and those have been updated to `> [!WARNING]` which is the correct down for Markdown rendering and the one we're converting into HuggingFace-formatting as `<Tip warning>`.
> Add reference to GitHub in documentation examples

- examples/gke/tei-deployment/README.md
- examples/gke/tei-from-gcs-deployment/README.md
- examples/gke/tgi-deployment/README.md
- examples/gke/tgi-from-gcs-deployment/README.md
- examples/gke/tgi-llama-405b-deployment/README.md
- examples/gke/tgi-llama-vision-deployment/README.md
- examples/gke/tgi-multi-lora-deployment/README.md
- examples/gke/trl-full-fine-tuning/README.md
- examples/gke/trl-lora-fine-tuning/README.md
This PR just adds the `git clone` command before the `kubectl apply -f` so that the users know where does the configuration come from; this is an iteration after #114, since even though the GitHub references have been included, is still not so clear where do those files come from; adding the `git clone` command leaves no space for doubt.
> Add missing `git clone` command in `examples/gke/*`

- containers/pytorch/inference/cpu/2.2.2/transformers/4.41.1/py311/Dockerfile
- containers/pytorch/inference/cpu/2.2.2/transformers/4.41.1/py311/entrypoint.sh
- containers/pytorch/inference/cpu/2.2.2/transformers/4.44.0/py311/entrypoint.sh
- containers/pytorch/inference/gpu/2.2.2/transformers/4.41.1/py311/Dockerfile
- containers/pytorch/inference/gpu/2.2.2/transformers/4.41.1/py311/entrypoint.sh
- containers/pytorch/inference/gpu/2.2.2/transformers/4.44.0/py311/entrypoint.sh
This PR fixes the version of `huggingface-inference-toolkit` pinned within both DLCs:
- us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-pytorch-inference-cu121.2-2.transformers.4-41.ubuntu2204.py311
- us-docker.pkg.dev/deeplearning-platform-release/gcr.io/huggingface-pytorch-inference-cpu.2-2.transformers.4-41.ubuntu2204.py311
As the `huggingface-inference-toolkit` version was pinned to a more recent one (0.4.2) instead of 0.4.1, that's due to the version pinning on `huggingface-inference-toolkit` that happened before releasing it publicly.
Additionally, this PR also adds the `exec` before the `uvicorn` command in the `entrypoint.sh` files so as to fix the signal handling for gracefully shutting it down.
Finally, this PR also installs the correct version of …
> Fix `entrypoint.sh` and `huggingface-inference-toolkit` version in PyTorch Inference DLCs

- containers/pytorch/inference/cpu/2.2.2/transformers/4.41.1/py311/Dockerfile
- containers/pytorch/inference/gpu/2.2.2/transformers/4.41.1/py311/Dockerfile
This PR is a follow up of #120 as reported by @xuyifann due to a missing dependency for `google-cloud-storage` within the Hugging Face PyTorch DLC for Inference on both CPU and GPU for the `transformers` version 4.41.0; as when patching the DLC in #120, that dependency was missing, but was catched during the testing after building the DLC.
This PR then adds the missing `google-cloud-storage` dependency within the Dockerfile, to patch that exact DLC, whilst the rest work fine, since those dependencies are installed as part of the `google` extra of `huggingface-inference-toolkit`, not available within the pinned `huggingface-inference-toolkit` version installed in this DLC in particular.
> Add missing `google-cloud-storage` dependency in PyTorch DLC

- containers/pytorch/inference/cpu/2.2.2/transformers/4.41.1/py311/Dockerfile
- containers/pytorch/inference/gpu/2.2.2/transformers/4.41.1/py311/Dockerfile
As a follow up of #124, this PR updates the pinned version so that it points to https://github.com/huggingface/huggingface-inference-toolkit/pull/76 instead, as it contains a fix for the Google Cloud Storage (GCS) path downloads.
To reproduce locally one can run the following:
> [!WARNING]
> The command below assumes that `huggingface-pytorch-inference-cpu.2.2.2.transformers.4.41.0.py311` is the local Docker image name built as:
> ```bash
> docker build --platform=linux/amd64 -t huggingface-pytorch-inference-cpu.2.2.2.transformers.4.41.0.py311 -f containers/pytorch/inference/cpu/2.2.2/transformers/4.41.1/py311/Dockerfile .
> ```
>
> And that the `AIP_STORAGE_URI` is pointing to a valid bucket on GCS, with a Transformers compatible model.
```bash
docker run --platform linux/amd64 -v …
```
> Fix pinned `huggingface-inference-toolkit` to include path patch

- containers/tgi/gpu/3.0.1/Dockerfile
- containers/tgi/gpu/3.0.1/entrypoint.sh
This PR adds the new container for TGI v3.0.1 recently released (see https://github.com/huggingface/text-generation-inference/releases/tag/v3.0.1).
The main features w.r.t. the previous major release from TGI, as of the words from the TGI team themselves:
- Processes 3x more tokens: By reducing our memory footprint, we’re able to ingest many more tokens and more dynamically than before. A single L4 (24GB) can handle 30k tokens on llama 3.1-8B, while vLLM gets barely 10k. A lot of work went into reducing the footprint of the runtime and its effect are best seen on smaller constrained environments.
- 13x faster: On long prompts (200k+ tokens) conversation replies take 27.5s in vLLM, while it takes only 2s in TGI. We keep the initial conversation around, so when a new reply comes in, we can …
> Add `containers/tgi/gpu/3.0.1`

- containers/tei/cpu/1.6.0/Dockerfile
- containers/tei/cpu/1.6.0/entrypoint.sh
- containers/tei/gpu/1.6.0/Dockerfile
- containers/tei/gpu/1.6.0/entrypoint.sh
This PR adds a new container for TEI v1.6.0 just released (see the release notes at https://github.com/huggingface/text-embeddings-inference/releases/tag/v1.6.0).
The main feature on TEI v1.6.0 w.r.t. TEI v1.5.0 is that it now supports multiple CPU backends, not just ONNX, meaning that it can also serve embedding models on CPU with backends other than ONNX (since not every model on the Hub comes with an ONNX-converted version of the weights). Some other features include the addition of the General Text Embeddings (GTE) heads, the implementation of MPNet, fixes around the health checks, and much more.
> [!NOTE]
> Note that this PR also includes the changes from the https://github.com/huggingface/text-embeddings-inference/releases/tag/v1.5.1 release.
To inspect the changes required to make …
> Add `containers/tei/{cpu,gpu}/1.6.0`

- containers/tei/cpu/1.2.2/Dockerfile
- containers/tei/cpu/1.4.0/Dockerfile
- containers/tei/cpu/1.5.1/Dockerfile
- containers/tei/gpu/1.2.2/Dockerfile
- containers/tei/gpu/1.4.0/Dockerfile
- containers/tei/gpu/1.5.1/Dockerfile
- containers/tei/gpu/1.6.0/Dockerfile
This PR pins the `cargo-chef` version being installed on the `Dockerfile` images for TEI on CUDA, since the latest raises the following issue when running `cargo chef prepare --features google --recipe-path recipe.json` with the following exception:
```
0.294 error: failed to parse manifest at `/usr/src/router/Cargo.toml`                                                                                                                                                                                       
0.294                                                                                                                                                                                                                                                       
0.294 Caused by: …
```
> Pin `cargo-chef` version on TEI DLCs on GPU

- examples/gke/tei-deployment/cpu-config/deployment.yaml
- examples/gke/tei-deployment/gpu-config/deployment.yaml
- examples/gke/tgi-deployment/config/deployment.yaml
- examples/gke/tgi-llama-405b-deployment/config/deployment.yaml
- examples/gke/tgi-llama-vision-deployment/config/deployment.yaml
- examples/gke/tgi-multi-lora-deployment/config/deployment.yaml
This PR updates some `mountPath` references that were still pointing to `/data` instead of `/tmp`; whilst `/data` was the default `HF_HOME` only in [the default TGI Dockerfile within the TGI repository](https://github.com/huggingface/text-generation-inference/blob/main/Dockerfile), and within the following (already published) TGI DLCs on Google Cloud: [TGI 1.4.2](https://github.com/huggingface/Google-Cloud-Containers/blob/1c31c519b71cda5329bb7284ad521429302b7b73/containers/tgi/gpu/1.4.2/Dockerfile#L186), [TGI 1.4.4](https://github.com/huggingface/Google-Cloud-Containers/blob/1c31c519b71cda5329bb7284ad521429302b7b73/containers/tgi/gpu/1.4.4/Dockerfile#L186), [TGI 2.0.0](https://github.com/huggingface/Google-Cloud-Containers/blob/1c31c519b71cda5329bb7284ad521429302b7b73/containers/tgi/gpu/2. …
> Fix `mountPath` to use `/tmp` instead of `/data`

- docs/source/_toctree.yml
- docs/source/tpu.mdx
This PR adds a link to optimum-tpu in the docs so that users of Google Cloud that are interested in TPUs can look at optimum-tpu for more in-depth information on TPUs
> Add details about TPUs in the docs

- containers/pytorch/training/tpu/2.5.1/transformers/4.46.3/py310/Dockerfile
This is just to align training container with optimum-tpu 0.2.3 used in TGI container.
> feat(tpu): updated to optimum 0.2.3, added llama training example
